name: Build Marmara Connector

on:
  push:
    branches: 
      - '*'  # Срабатывание на любые изменения в любых ветках
  pull_request:
    branches: 
      - '*'  # Срабатывание на pull request в любые ветки

jobs:
  build_Debian:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install dependencies and build app
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            python3-dev \
            python3 \
            python3-pip \
            python3-venv \
            qttools5-dev-tools \
            python3-pyqt5 \
            ruby ruby-dev rubygems build-essential

          # Создание и активация виртуального окружения
          python3 -m venv venv
          source venv/bin/activate
          
          sudo gem install --no-document fpm
          fpm --version    
          pip install --upgrade pip wheel
          pip install -r requirements.txt

          # Сборка приложения
          fbs freeze
          fbs installer

      - name: Upload Build Artifacts (Linux)
        uses: actions/upload-artifact@v4.0.0
        with:
          path: target/*.deb
          retention-days: 7

      - name: Upload Build Artifacts (Linux Portable)
        uses: actions/upload-artifact@v4.0.0
        with:
          path: target/MarmaraConnector-*
          retention-days: 7
          
  build_Windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8.x"

      - name: Install dependencies
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          python -m pip install pywin32
          pip install -r requirements.txt

      - name: Run fbs and freeze app
        shell: powershell
        run: |
          fbs freeze
          fbs installer

      - name: Upload Build Artifacts (Windows executable)
        uses: actions/upload-artifact@v4.0.0
        with:
          path: .\target\*.exe
          retention-days: 7

      - name: Upload Build Artifacts (Windows Portable)
        uses: actions/upload-artifact@v4.0.0
        with:
          path: .\target\MarmaraConnector*
          retention-days: 7
